export const config = { runtime: 'edge' };

export default async function handler(req: Request): Promise<Response> {
  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 });
  }

  const { profile, medications, logs, concerns } = await req.json();

  const today = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  const symptomSummary = buildSymptomSummary(logs);

  const prompt = `You are generating a formal menstrual health summary report for a patient to share with their GP or healthcare provider. Write in clear, clinical British English. Be factual and specific. Do not speculate beyond the data provided.

Patient data:
- Name: ${profile.name}
- Average cycle length: ${profile.cycle_length} days
- Average period length: ${profile.period_length} days
- Last period start: ${profile.last_period_start ?? 'not recorded'}
- Current medications: ${medications.length > 0 ? medications.join(', ') : 'none recorded'}
- Data covers: last ${logs.length} daily logs

Symptom frequency (from logs):
${symptomSummary}

${concerns ? `Patient's specific concerns to address: ${concerns}\n` : ''}
Generate a GP report with the following sections:
1. Patient Summary
2. Menstrual Cycle Overview
3. Current Medications
4. Symptom Patterns (past 3 months)
5. Energy and Wellbeing Trends
6. Patient's Concerns${concerns ? ' (address these specifically)' : ' (none noted)'}
7. Notes for Clinician

End with a brief disclaimer that this report was generated by a self-tracking application and is intended to support, not replace, clinical assessment.

Date of report: ${today}`;

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': process.env.ANTHROPIC_API_KEY ?? '',
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-6',
      max_tokens: 2048,
      messages: [{ role: 'user', content: prompt }],
    }),
  });

  if (!response.ok) {
    return new Response('API error', { status: 500 });
  }

  const data = await response.json();
  const text: string = data.content?.[0]?.text ?? '';

  return new Response(JSON.stringify({ text }), {
    headers: { 'Content-Type': 'application/json' },
  });
}

function buildSymptomSummary(logs: any[]): string {
  if (!logs.length) return 'No logs available.';

  const symptomCount: Record<string, number> = {};
  const energyTotal: number[] = [];

  for (const log of logs) {
    const all = [...(log.physical_symptoms ?? []), ...(log.emotional_symptoms ?? [])];
    for (const s of all) {
      symptomCount[s] = (symptomCount[s] ?? 0) + 1;
    }
    if (log.energy) energyTotal.push(log.energy);
  }

  const sorted = Object.entries(symptomCount)
    .sort((a, b) => b[1] - a[1])
    .map(([symptom, count]) => `- ${symptom}: ${count} day(s)`);

  const avgEnergy = energyTotal.length
    ? (energyTotal.reduce((a, b) => a + b, 0) / energyTotal.length).toFixed(1)
    : 'not recorded';

  return [
    ...sorted,
    `- Average energy level: ${avgEnergy}/5`,
  ].join('\n');
}
